language: cpp
sudo: required
dist: trusty
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - clang-3.7

compiler: gcc
env: COMPILER=g++-5 

matrix:
  exclude:

  include:
    - os: linux
      dist: trusty 
      env: COMPILER=clang++-3.7
      compiler: clang
      
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

before_install:
  - sudo apt-get -q update

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make 
  - ./test_concurrent
