language: cpp
sudo: required
dist: trusty
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.7
    packages:
      - g++-5
      - clang-3.7
      

compiler: gcc
env: COMPILER=g++-5 

matrix:
  exclude:

  include:
    - os: linux
      dist: trusty 
      env: COMPILER=clang++-3.7
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.7
          packages:
            - clang-3.7
            - clang++-3.7
      

before_install:
  - sudo apt-get -q update

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make 
  - ./test_concurrent
